#!/bin/bash
echo jsons/31*.json | xargs geojson-merge --stream > pop31.json
echo jsons/53*.json | xargs geojson-merge --stream > pop53.json
echo jsons/35*.json | xargs geojson-merge --stream > pop35.json
echo jsons/72*.json | xargs geojson-merge --stream > pop72.json
echo jsons/46*.json | xargs geojson-merge --stream > pop46.json
echo jsons/48*.json | xargs geojson-merge --stream > pop48.json
#echo jsons/06*.json | xargs geojson-merge --stream > pop06.json
echo jsons/21*.json | xargs geojson-merge --stream > pop21.json
echo jsons/39*.json | xargs geojson-merge --stream > pop39.json
#echo jsons/01*.json | xargs geojson-merge --stream > pop01.json
echo jsons/13*.json | xargs geojson-merge --stream > pop13.json
echo jsons/55*.json | xargs geojson-merge --stream > pop55.json
#echo jsons/05*.json | xargs geojson-merge --stream > pop05.json
echo jsons/41*.json | xargs geojson-merge --stream > pop41.json
echo jsons/42*.json | xargs geojson-merge --stream > pop42.json
echo jsons/28*.json | xargs geojson-merge --stream > pop28.json
echo jsons/29*.json | xargs geojson-merge --stream > pop29.json
echo jsons/08*.json | xargs geojson-merge --stream > pop08.json
echo jsons/37*.json | xargs geojson-merge --stream > pop37.json
echo jsons/49*.json | xargs geojson-merge --stream > pop49.json
echo jsons/40*.json | xargs geojson-merge --stream > pop40.json
echo jsons/51*.json | xargs geojson-merge --stream > pop51.json
echo jsons/47*.json | xargs geojson-merge --stream > pop47.json
echo jsons/56*.json | xargs geojson-merge --stream > pop56.json
echo jsons/54*.json | xargs geojson-merge --stream > pop54.json
echo jsons/22*.json | xargs geojson-merge --stream > pop22.json
#echo jsons/36*.json | xargs geojson-merge --stream > pop36.json
echo jsons/26*.json | xargs geojson-merge --stream > pop26.json
echo jsons/18*.json | xargs geojson-merge --stream > pop18.json
echo jsons/25*.json | xargs geojson-merge --stream > pop25.json
echo jsons/20*.json | xargs geojson-merge --stream > pop20.json
echo jsons/16*.json | xargs geojson-merge --stream > pop16.json
echo jsons/12*.json | xargs geojson-merge --stream > pop12.json
#echo jsons/02*.json | xargs geojson-merge --stream > pop02.json
echo jsons/78*.json | xargs geojson-merge --stream > pop78.json
echo jsons/32*.json | xargs geojson-merge --stream > pop32.json
echo jsons/17*.json | xargs geojson-merge --stream > pop17.json
echo jsons/50*.json | xargs geojson-merge --stream > pop50.json
echo jsons/09*.json | xargs geojson-merge --stream > pop09.json
echo jsons/30*.json | xargs geojson-merge --stream > pop30.json
echo jsons/34*.json | xargs geojson-merge --stream > pop34.json
echo jsons/27*.json | xargs geojson-merge --stream > pop27.json
echo jsons/38*.json | xargs geojson-merge --stream > pop38.json
echo jsons/24*.json | xargs geojson-merge --stream > pop24.json
echo jsons/19*.json | xargs geojson-merge --stream > pop19.json
echo jsons/45*.json | xargs geojson-merge --stream > pop45.json
echo jsons/23*.json | xargs geojson-merge --stream > pop23.json
echo jsons/15*.json | xargs geojson-merge --stream > pop15.json
echo jsons/33*.json | xargs geojson-merge --stream > pop33.json
#echo jsons/04*.json | xargs geojson-merge --stream > pop04.json
echo jsons/10*.json | xargs geojson-merge --stream > pop10.json
echo jsons/11*.json | xargs geojson-merge --stream > pop11.json
echo jsons/66*.json | xargs geojson-merge --stream > pop66.json
echo jsons/69*.json | xargs geojson-merge --stream > pop69.json
echo jsons/60*.json | xargs geojson-merge --stream > pop60.json
echo jsons/44*.json | xargs geojson-merge --stream > pop44.json
tippecanoe -z12 -o people-usa.mbtiles -l people-usa --drop-densest-as-needed *.json